name: Rust CI
on:
  pull_request:
  push:
    branches: ['main']

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Add `rustfmt` to toolchain
        run: rustup +nightly component add rustfmt
      - name: Format
        run: cargo +nightly fmt --check
  
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            sdk/rust

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Check
        run: cargo check --workspace
        
  
  test:
    needs: ['check']
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            .

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: cargo test --workspace
